[project]
name = "tufts-coldfront-plugins"
version = "0.2.0"
description = "Plugins for Tufts ColdFront system."
authors = [
	{ name = "Chris Barnett", email = "christopher.barnett@tufts.edu" }
]
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["high-performance-computing", "resource-allocation"]
classifiers = [
    'Programming Language :: Python :: 3',
    'Framework :: Django :: 6.0',
    'Topic :: Scientific/Engineering',
    'Topic :: System :: Systems Administration',
    'Topic :: Internet :: WWW/HTTP :: WSGI :: Application',
]
dependencies = [
    "coldfront==1.1.7",
    "pyinfra>=3.10.0,<=3.11.0",
]

[dependency-groups]
dev = [
    "pre-commit",
    "ruff",
    "pytest",
    "pytest-django",
    "pytest-cov>=7.1.0",
    "pytest-xdist>=3.8.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["tufts_local"]

[tool.hatch.metadata]
allow-direct-references = true

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "Q", "S308"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"

[tool.ruff.format]
indent-style = "space"
docstring-code-format = true
quote-style = "single"

[tool.ruff.lint.isort]
sections = { "coldfront-main" = ["coldfront"] }
section-order = [
    "future",
    "standard-library",
    "third-party",
    "coldfront-main",
    "first-party",
    "local-folder",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "tufts_local.tests.settings"
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = [
    "--strict-markers",
    "--tb=short"
]
markers = [
    "django_db: marks tests as requiring database access",
]
testpaths = ["tufts_local/tests"]
