# Generated by Django 4.2.30 on 2026-09-21 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='IgnoredTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'field',
                    models.CharField(
                        choices=[('name', 'Task name (starts with)'), ('group', 'Group id (exact)')],
                        default='name',
                        help_text='Which part of the task to match against.',
                        max_length=5,
                    ),
                ),
                (
                    'pattern',
                    models.CharField(
                        help_text='Task names match on a prefix, so add_sf_tags hides every add_sf_tags_alloc_activate_<id> task. Group ids must match in full. Matching ignores case.',
                        max_length=100,
                    ),
                ),
                (
                    'reason',
                    models.CharField(
                        blank=True, help_text='Optional note about why these tasks are hidden.', max_length=255
                    ),
                ),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ignored task',
                'verbose_name_plural': 'ignored tasks',
                'ordering': ['field', 'pattern'],
                'unique_together': {('field', 'pattern')},
            },
        ),
    ]
