# Generated by Django 4.2.30 on 2026-09-29 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        # relaxed from the generated pin on django_q's latest migration: all this needs is
        # the Task table, which its 0001 creates, and pinning would force a django-q floor
        # on every deployment for no reason
        ('django_q', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tufts_local', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAcknowledgement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True)),
                (
                    'reason',
                    models.CharField(
                        blank=True,
                        help_text='Optional note about why this failure is nothing to worry about.',
                        max_length=255,
                    ),
                ),
                (
                    'acknowledged_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='+',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'task',
                    models.OneToOneField(
                        help_text='The failed task being acknowledged.',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='acknowledgement',
                        to='django_q.task',
                    ),
                ),
            ],
            options={
                'verbose_name': 'task acknowledgement',
                'verbose_name_plural': 'task acknowledgements',
                'ordering': ['-acknowledged_at'],
            },
        ),
    ]
